version: '3.8'

services:
  
  redis:
    image: redis:7-alpine
    container_name: crawler-redis
    ports:
      - "6379:6379"

   Elasticsearch
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: crawler-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"